### ISSUE TITLE
A mistake in Reference->Syntax->Functions->Applications

### ISSUE THREAD

**Issue by lwshang** [KxSystems/docs-v1#35]
In the section mentioned in the title, there is a line saying:

> A unary function `g` with argument `d` can be evaluated by `g@d` or `g.enlist d`.

The mistake is in the last code which use `.` apply. The correct using of it requires spaces on both sides of the dot. Therefore, this line should be:

> A unary function `g` with argument `d` can be evaluated by `g@d` or `g . enlist d`.

**Comment by WillDaSilva** [comment]
I've made a pull request with the change you mentioned, as well as one other to the same file.
https://github.com/KxSystems/docs/pull/34

**Comment by ghost** [comment]
Thanks for the catch!
