### ISSUE TITLE
Question about null `::` in Reference->Unclassified

### ISSUE THREAD

**Issue by lwshang** [KxSystems/docs-v1#36]
In the section mentioned in the title, the last point about null `::` says that it can be used to "prevent a mixed list from being coerced into a vector". While I don't think this is a good trick with `::`.

```
q)x:(1;2;3)
q)count x
3
q)type x
7h
q)y:(::;1;2;3)
q)count y
4
q) type y
0h
```

It's obvious that the use of `::` has a side effect which extend the length of the list.

In fact, I find out that there will be no problem if we avoid using `,:`.

```
q)x,:`a
'type
q)x:x,`a
q)x
1
2
3
`a
```

In fact this behavior of `,:` is more universal with different data types:

```
q)a:1
q)a,:2
'type
q)a:a,2
q)a
1 2
q)type a
7h
```

I would consider this behavior of `,:` as a bug.

**Comment by ghost** [comment]
Your discussion on the k4 listbox deals with this, I think.
